name: fusion-env
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope
  - asttokens
- blas
- brotli-bin
- brotli
- bzip2
- ca-certificates
- comm
- contourpy
- cycler
- debugpy
- decorator
- executing
- expat
- fonttools
- freetype
- ipykernel
- ipython
- jedi
- jpege
- jupyter_client
- jupyter_core
- kiwisolver
- lcms2
- lerc
- libbrotlicommon
- libbrotlidec
- libbrotlienc
- libcxx
- libdeflate
- libffi
- libgfortran5
  - libgfortran_3_0_hca03da5_28
- libopenblas
- libpng
- libsodium
- libtiff
- libwebp-base
- llvm-openmp
- lz4-c
- matplotlib-base
- matplotlib-inline
- matplotlib
- ncurses
- nest-asyncio
- numpy-base
- numpy
- openjpeg
- openssl
- packaging
- parso
- pexpect
- pillow
- pip
- platformdirs
- prompt-toolkit
- prompt_toolkit
- psutil
- ptyprocess
- pure_eval
- pygments
- pyparsing
- python-dateutilpost0
- python
- pyzmq
- readline
- setuptools
- six
- sqlite
- stack_data
- tk
- tornado
- traitlets
- unicodedata2
- wcwidth
- wheel
- xz
- zeromq
- zlib
- zstd

